### ISSUE TITLE
American Truck Simulator

### ISSUE THREAD

**Issue by quimbydogg** [lhark/truckersmp-cli#1]
After struggling to get the official multiplayer mod working with wine I stumbled across your project.  Really like the work you have done with this launcher, it was easy to setup and have everything work.  Do you have any plans to implement support for American Truck Simulator as well?

Thanks

**Comment by lhark** [comment]
I feared the day this question would come ^^ It's just laziness on my part and it should be relatively easy to implement (take a look at the code). However i don't own american truck simulator so i can't test anything :/

Actually, if you feel like implementing a quick and dirty fix, i think the only lines you need to change are https://github.com/lhark/truckersmp-cli/blob/master/truckersmp-cli.c#L28
https://github.com/lhark/truckersmp-cli/blob/master/truckersmp-cli.c#L29
and also
https://github.com/lhark/truckersmp-cli/blob/master/truckersmp-cli.c#L46
https://github.com/lhark/truckersmp-cli/blob/master/truckersmp-cli.c#L47
where the game ID should be 270880

You could also tell what the name and the path of the executable is. I could use that to create an American branch.

Obviously the clean solution is for me to implement a real switch in the options ^^

**Comment by quimbydogg** [comment]
Thanks for the quick reply on this!

I don't have Mingw setup on my system.  It would be great if you could make an American branch.

The ATS executable path is \\bin\\win_x64\\amtrucks.exe

**Comment by lhark** [comment]
I pushed a new branch, you can try to checkout "ats" and see if that works. No guarantee though, it has thoroughly NOT been tested :)

**Comment by quimbydogg** [comment]
It looks like there is an extra 2 in the exe path:
https://github.com/lhark/truckersmp-cli/blob/ats/truckersmp-cli.c#L28
This should just be amtrucks.exe

I'll take it as a good sign the launcher got all the way to the ATS executable before having an issue :)

Thanks again for your help with this, greatly appreciated!

**Comment by lhark** [comment]
Sorry about that, it should be fixed now.

**Comment by quimbydogg** [comment]
Works great!

**Comment by lhark** [comment]
Nice, thank you for your feedback :)
