### ISSUE TITLE
truckersmp-cli error

### ISSUE THREAD

**Issue by PawelGluszek** [lhark/truckersmp-cli#108]
What should I do?

`truckersmp-cli 
Traceback (most recent call last):
  File "/home/pawel/.local/bin/truckersmp-cli", line 12, in <module>
    main()
TypeError: 'module' object is not callable`

**Comment by Lucki** [comment]
> What should I do?

You should…

> […] [make sure you're using the provided issue template this time.](https://github.com/lhark/truckersmp-cli/issues/107#issuecomment-701496872)

Since it is already open and you've ignored it now twice you can find it [here](https://raw.githubusercontent.com/lhark/truckersmp-cli/master/.github/ISSUE_TEMPLATE/bug_report.md).
