### ISSUE TITLE
Error with truckersmp-cli

### ISSUE THREAD

**Issue by PawelGluszek** [lhark/truckersmp-cli#109]
[comment]: # (Run your command with additional informational output [-v] and try to pinpoint the problem first.)

## Describe the bug
After running command `truckersmp-cli` i got an error and i have no idea how i can fix it

## Expected behavior
Not an error

## Command
~~~
truckersmp-cli -v
~~~

## Terminal output
<details><summary>Log
</summary>

~~~
Traceback (most recent call last):
  File "/home/pawel/.local/bin/truckersmp-cli", line 12, in <module>
    main()
TypeError: 'module' object is not callable

~~~
</details>

## Screenshots
<details><summary>
Screenshots
</summary>

[comment]: # (If applicable, add screenshots to help explain your problem:)
![image](https://user-images.githubusercontent.com/29426967/94713805-93adbf00-034b-11eb-8c5b-cfde1e785847.png)

</details>

## Information
 - OS: Ubuntu 20.04
 - Proton or Wine version: Wine-5.0
 - truckersmp-cli version: 0.1.0

**Comment by kakurasan** [comment]
@PawelGluszek Could you reinstall for Python 3 (`python3 -m pip install truckersmp-cli[optional]`) and retry?

**Comment by Lucki** [comment]
Closing in lack of feedback.

This error is most likely caused by not respecting the requirements ([python in version 3.3 (released in September 2012) or later](https://github.com/lhark/truckersmp-cli#required)).
