### ISSUE TITLE
Can't launch TruckersMP Because Of Wine Discord Ipc Bridge

### ISSUE THREAD

**Issue by RoyvanEmpel** [lhark/truckersmp-cli#120]
Hello,

I am running debian and just downloaded the truckersmp-cli and ran `./truckersmp-cli -eups` and after it downloaded the game and tried to start it is giving me this error in the CMD which opens: `Pipe Server: Main thread awaiting client connection on \\.\pipe\discord-ipc-0`.

When trying the `--without-wine-discord-ipc-bridge` command it won't even open a cmd it just crashes after a few seconds. (Empty log with `-l log.txt`)

Hopefully there is a simple solution/fix

Greetings,
Roy

**Comment by RoyvanEmpel** [comment]
Whoops already fixed it.

I manually installed it and thats what i did wrong xD. Ran the python installation command with sudo and now its working without any problems.

**Comment by Lucki** [comment]
Duplicate of #92
