### ISSUE TITLE
TruckersMP overlay doesn't appear on DXVK even with native d3dcompiler_47.dll

### ISSUE THREAD

**Issue by z411** [lhark/truckersmp-cli#130]
[comment]: # (Run your command with additional informational output [-v] and try to pinpoint the problem first.)

## Describe the bug
I can't login as the TruckersMP login overlay doesn't appear when running with Proton+DXVK (-p -d) even with the native d3dcompiler_47.dll. The game also crashes when closing it (doesn't happen on OpenGL). Note that it has worked a few times (2 times out of probably the 15 times I've tried).

## Expected behavior
The TruckersMP login overlay should appear. It works fine with OpenGL.

## Command
~~~
truckersmp-cli --account z411 --ets2 --beta temporary_1_38 --proton --enable-d3d11 --disable-proton-overlay --activate-native-d3dcompiler-47 --start -vv
~~~

## Terminal output
<details><summary>Collapsed log</summary>

~~~
** DEBUG **  No moddir set, setting to default
** INFO **  Mod directory: /home/z411/.local/share/truckersmp-cli/TruckersMP
** INFO **  AppID/GameID: 227300 (ets2)
** INFO **  Game directory: /home/z411/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
** INFO **  Prefix: /home/z411/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
** INFO **  Proton directory: /home/z411/.local/share/truckersmp-cli/Proton
** DEBUG **  Updating mod files
** DEBUG **  No files to download
** DEBUG **  Starting game with Proton
** DEBUG **  Steam is running
** INFO **  Steam installation directory: /home/z411/.local/share/Steam
** DEBUG **  d3dcompiler_47.dll is present, MD5 is OK.
** DEBUG **  Copying d3dcompiler_47.dll into /home/z411/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/drive_c/windows/system32
** DEBUG **  Adding DLL override setting for eurotrucks2.exe
esync: up and running.
The registry value 'd3dcompiler_47' already exists. Do you want to overwrite it? (Yes|No)yes
The operation completed successfully
** DEBUG **  winediscordipcbridge.exe is present, MD5 is OK.
** INFO **  Starting winediscordipcbridge.exe
** INFO **  Startup command:
  SteamGameId=227300
  SteamAppId=227300
  STEAM_COMPAT_DATA_PATH=/home/z411/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
  STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/z411/.local/share/Steam
  PROTON_USE_WINED3D=0
  PROTON_NO_D3D11=0
  /usr/bin/python /home/z411/.local/share/truckersmp-cli/Proton/proton
  run
  /usr/lib/python3.8/site-packages/truckersmp_cli/truckersmp-cli.exe /home/z411/.local/share/truckersmp-cli/Euro Truck Simulator 2/data /home/z411/.local/share/truckersmp-cli/TruckersMP
** INFO **  Proton output:
esync: up and running.
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198031943586 [API loaded no]
Fossilize INFO: Overriding serialization path: "/mnt/ext4/Steam/steamapps/shadercache/227300/fozpipelinesv4/steamapprun_pipeline_cache".
Fossilize INFO: Overriding serialization path: "/mnt/ext4/Steam/steamapps/shadercache/227300/fozpipelinesv4/steamapprun_pipeline_cache".
wine: Unhandled page fault on read access to 00007F3320D88A10 at address 0000000140125029 (thread 011c), starting debugger...

~~~
</details>

## Screenshots
<details><summary>Collapsed screenshots</summary>

[comment]: # (If applicable, add screenshots to help explain your problem:)
![Screenshot_20201115_015248](https://user-images.githubusercontent.com/1988512/99168601-73607680-26e5-11eb-9c48-0b24553afcbd.png)

</details>

## Information
 - OS: Arch Linux
 - Proton or Wine version: `Proton 5.0 and 5.13`
 - truckersmp-cli version: `0.2.2`

**Comment by kakurasan** [comment]
When switching from newer Proton version to older, the native `d3dcompiler_47.dll` is removed (replaced with built-in DLL) by downgrading prefix automatically.

The native `d3dcompiler_47.dll` itself works for me (able to logged in) with Proton 5.0 and 5.13.

We can change `main.py` to start `wineboot` beforehand to allow Proton to "downgrade" the prefix before copying the native DLL (`--activate-native-d3dcompiler-47` is still needed only when switching Proton version), but cannot protect it (For example, `chmod 444 /path/to/proton_prefix/pfx/drive_c/windows/system32/d3dcompiler_47.dll` does not work for me).

**Comment by z411** [comment]
I didn't switch from newer to older version, in fact I tried with 5.0 a few times before trying with 5.13 also with the same result. You can also see in the log that I overwrote the .dll. I assume this might have to do with the combination of hardware/drivers and Proton... I might try with Wine.

**Comment by kakurasan** [comment]
> I didn't switch from newer to older version, in fact I tried with 5.0 a few times before trying with 5.13 also with the same result. You can also see in the log that I overwrote the .dll. ...

Indeed it's weird, but unfortunately I could reproduce only when switching Proton version. This might be different from your issue.

In your case, it might be helpful to provide `client_[YYYY]_[MM]_[DD].log` ([logs directory](https://github.com/lhark/truckersmp-cli/blob/master/README.md#game-logs)) additionally because it might contain D3D11 related messages.

**Comment by z411** [comment]
Fixed by disabling KDE's compositor. My guess is that KWin's compositor is doing something to the window akin to alt-tabbing it when it unredirects the window, which is triggering the alt-tab bug right at the start. Nonetheless, thank you for your advice.

**Comment by kakurasan** [comment]
Congrats, but unfortunately I cannot reproduce on my Kubuntu 20.10 (works with `kwin_x11` + compositing and `kwin_wayland`).

@Lucki Can you test with KWin on your distro?

**Comment by Lucki** [comment]
> @Lucki Can you test with KWin on your distro?

Finally came around installing plasma (omg is that slow) and also can't reproduce on arch + x11 + plasma (kwin?) + opengl 3.1 compositing.
