### ISSUE TITLE
Truckersmp not launch

### ISSUE THREAD

**Issue by TheStami** [lhark/truckersmp-cli#133]
I have a problem. After type a command: `truckersmp-cli --ets2 --start ` launching Truckersmp console:
![image](https://user-images.githubusercontent.com/62695938/99905242-f8442500-2ccf-11eb-90a2-dfa786e02493.png)
And second console window with text: `Pipe Server: Main thread awaiting client on \\.\pipe\discord-ipc-0`. I try to use `--without-wine-discord-ipc-bridge` arg, but then open only main console widow bud game still not. In steam ets views as running. What I can solve this problem?

**Comment by Lucki** [comment]
I don't see any errors, TruckersMP needs some time to start up.

Unfortunately you ignored our precious issue template when creating this issue so I have to ask for additional information. Please fill out the issue template. You can find the latest issue template here: https://raw.githubusercontent.com/lhark/truckersmp-cli/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by TheStami** [comment]
> Unfortunately you ignored our precious issue template when creating this issue so I have to ask for additional information. 

Oh, sure, sorry.

Output of `truckersmp-cli --ets2 --start -vv` command is:
```
** DEBUG **  No moddir set, setting to default
** INFO **  Mod directory: /home/a15/.local/share/truckersmp-cli/TruckersMP
** INFO **  Platform is Linux, using Proton
** INFO **  AppID/GameID: 227300 (ets2)
** INFO **  Game directory: /home/a15/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
** INFO **  Prefix: /home/a15/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
** INFO **  Proton directory: /home/a15/.local/share/truckersmp-cli/Proton
** DEBUG **  Updating mod files
** DEBUG **  No files to download
** DEBUG **  Starting game with Proton
** DEBUG **  Starting Steam...
                                                                      
** DEBUG **  Steam should be up now.
** INFO **  Steam installation directory: /home/a15/.local/share/Steam
** DEBUG **  winediscordipcbridge.exe is present, MD5 is OK.
** INFO **  Starting winediscordipcbridge.exe
** INFO **  Startup command:
  SteamGameId=227300
  SteamAppId=227300
  STEAM_COMPAT_DATA_PATH=/home/a15/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
  STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/a15/.local/share/Steam
  PROTON_USE_WINED3D=0
  PROTON_NO_D3D11=1
  LD_PRELOAD=/home/a15/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
  /usr/bin/python3 /home/a15/.local/share/truckersmp-cli/Proton/proton
  run
  /home/a15/.local/lib/python3.6/site-packages/truckersmp_cli/truckersmp-cli.exe /home/a15/.local/share/truckersmp-cli/Euro Truck Simulator 2/data /home/a15/.local/share/truckersmp-cli/TruckersMP
```
With `--without-wine-discord-ipc-bridge` output is same. Just not display window with `Pipe Server: Main thread awaiting client on \\.\pipe\discord-ipc-0`.
Game not run even a long time after type command.

OS: Ubuntu 18.04.05 LTS
Proton version: 5.0
truckersmp-cli version: 0.3.0

**Comment by Lucki** [comment]
Is your Steam client running and are you logged in?

**Comment by TheStami** [comment]
> Is your Steam client running and are you logged in?

Yes. It's the same situation when I run Steam before run truckersmp-cli and when truckersmp-cli run Steam autonomously.

**Comment by Lucki** [comment]
What's the output of `pgrep -u $USER -x steam`?

> `** INFO **  Steam installation directory: /home/a15/.local/share/Steam`

Is that steam installation directory correct?

**Comment by TheStami** [comment]
You right, steam installed for me in `/home/a15/.steam` Am I need to use special argument in truckersmp-cli (I can't see this in Usage Options) or do something else?



> What's the output of `pgrep -u $USER -x steam`?

```
21094
21266
21272
```

**Comment by Lucki** [comment]
It seems you're basically affected by #32 which is a bug we've fixed back in april.
A bit strange is that there's no "Application load error" window popping up, is it somewhere in the background?

The manual fix would be as described in https://github.com/lhark/truckersmp-cli/issues/34#issuecomment-504429293. Please follow the steps and correct the path for Steam in the command as Steam is not in `$XDG_DATA_HOME` on your system.

The cause of this is that we weren't able to find your steam installation. And I'd like to know why this happened but I can't see a potential failing point right now.
Did you already tried truckersmp-cli before april?

**Comment by TheStami** [comment]
So, I followed by instructions and it didn't work, but after that I'm just created symblic link in `/home/a15/.local/share/Steam` to my steam folder and this solved the problem.

> Did you already tried truckersmp-cli before april?

No. I first play ets few days ago and it's my first time with truckersmp-cli

**Comment by Lucki** [comment]
> solved the problem

Great to hear - although I hope this won't hit you in the back later on.
(And the initial issue isn't solved, @kakurasan if you have any idea what could've caused this, feel free to reopen)
