### ISSUE TITLE
Installation gives `ERROR! Failed to install app '1420170' (Invalid install path)`

### ISSUE THREAD

**Issue by ACH1980** [lhark/truckersmp-cli#148]
As mentioned above the installation gives `ERROR! Failed to install app '1420170' (Invalid install path)`

`ach1980@localhost:~$ truckersmp-cli --ets2 --update -n kettcardriverprofi
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/ach1980/.local/share/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Logging in user 'kettcardriverprofi' to Steam Public ...
Logged in OK
Waiting for user info...OK
ERROR! Failed to install app '1420170' (Invalid install path)
SteamCMD exited abnormally
`

**Comment by ACH1980** [comment]
OS is Debian 10

**Comment by Lucki** [comment]
Thanks for your bug report. It seems this has something to do with your locale.

Unfortunately you ignored our precious issue template when creating this issue so I have to ask for additional information. Please fill out the issue template. You can find the latest issue template here: https://raw.githubusercontent.com/lhark/truckersmp-cli/master/.github/ISSUE_TEMPLATE/bug_report.md

Additionally you may want to inspect your system `locale -a` and if there's no `en_US.UTF-8` rebuild your locale with that language set. There are more detailed information about this procedure in the [Arch wiki][wiki] which you may have to adapt to your distribution.

Additionally² you should have a look into `/home/ach1980/.local/share/Steam/logs/stderr.txt` which may have some more information.

[wiki]: https://wiki.archlinux.org/index.php/locale

**Comment by ACH1980** [comment]
Oh. The issue template wasn't shown when creating a issue. I'll try the locale thing and if it doesn't work I'll fill out that template for sure.

**Comment by ACH1980** [comment]
Ok, there's only en_GB installed. I'll install the other one too.

**Comment by ACH1980** [comment]
Ok, it doesn't helped. I'll send the more detailed description of the Issue according to the Issue template in a few Moments.

**Comment by ACH1980** [comment]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''
---

## Describe the bug
Failed to install

## Expected behavior
Installs TruckersMP

## Command
~~~
`truckersmp-cli --ets2 --update -n kettcardriverprofi`
~~~

## Terminal output
<details><summary>Collapsed log</summary>

~~~
`ach1980@localhost:~$ truckersmp-cli --ets2 --update -n kettcardriverprofi -vv
** DEBUG **  No moddir set, setting to default
** INFO **  Mod directory: /home/ach1980/.local/share/truckersmp-cli/TruckersMP
** INFO **  Platform is Linux, using Proton
** INFO **  AppID/GameID: 227300 (ets2)
** INFO **  Game directory: /home/ach1980/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
** INFO **  Prefix: /home/ach1980/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
** INFO **  Proton directory: /home/ach1980/.local/share/truckersmp-cli/Proton
** DEBUG **  Updating game files
** INFO **  SteamCMD: /home/ach1980/.local/share/truckersmp-cli/steamcmd/steamcmd.sh
** DEBUG **  Closing Linux version of Steam
Running Steam on debian 10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/ach1980/.local/share/Steam/ubuntu12_32/steam -shutdown
** DEBUG **  Updating Proton (AppID:1420170)
** INFO **  Command:
  /home/ach1980/.local/share/truckersmp-cli/steamcmd/steamcmd.sh
    +login kettcardriverprofi
    +force_install_dir /home/ach1980/.local/share/truckersmp-cli/Proton
    +app_update 1420170 validate
    +quit
Redirecting stderr to '/home/ach1980/.local/share/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...CreateBoundSocket: ::bind couldn't find an open port between 27060 and 27060
OK.
Logging in user 'kettcardriverprofi' to Steam Public ...
Logged in OK
Waiting for user info...OK
ERROR! Failed to install app '1420170' (Invalid install path)
SteamCMD exited abnormally
`
~~~
</details>

## Information
 - OS: Debian 10
 - Proton or Wine version: which is installed in steam? Multiple for different apps. But I can install any you want.
 - truckersmp-cli version: `0.4.1`

## Additional context
`~/.local/share/Steam/logs/stderr.txt`:
`CAppInfoCacheReadFromDiskThread took 67 milliseconds to initialize
CApplicationManagerPopulateThread took 1717 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)`

**Comment by Lucki** [comment]
Please update your steam client and try again.
https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3030328420762375736

**Comment by ACH1980** [comment]
It worked! Thanks.

P.S.: If you want to keep this issue open for other users until this is in Steam Stable just reopen it.
