### ISSUE TITLE
missing mute.txt

### ISSUE THREAD

**Issue by stormemann11** [lhark/truckersmp-cli#164]
when i try to start truckersmp-cli i get an issue that says that mute.txt is missing

**Comment by Lucki** [comment]
Unfortunately you ignored our precious issue template when creating this issue so I have to ask for additional information. Please fill out the issue template. You can find the latest issue template here: https://raw.githubusercontent.com/lhark/truckersmp-cli/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Lucki** [comment]
Great to hear your issue is solved.
It would be gladly appreciated if you elaborate how you've solved the issue in case other user stumble across the same issue.

**Comment by stormemann11** [comment]
I made the file in the prefix's ets2mp folder (in "My Documents") and typed in "0 0 0 0 0 0 0 0 0 0 0 0 0 0" and save then it worked.
I found out how to fix this by checking the same file on my windows box and typing in the same as it said in that file.
