### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by kyndek** [lhark/truckersmp-cli#2]
The script doesn't work anymore. It looks the links in the script are not correct and doesn't download necessary files anymore. Please fix this issue. Thanks.

**Comment by lhark** [comment]
Hi,
I just tested, and both URL are working fine on my side (update.ets2mp.com and download.ets2mp.com).
Could you be more precise with your report. How did you determine the URL are enreachable ?

**Comment by kyndek** [comment]
Ok, my bad. The urls works fine. But I've found an issue in the script. The "files" variable uses awk command  with filter by "FAILED" word. A national version of bash (in my case polish) translate this word to own language (in my case failed=niepowodzenie) Thats why the script doesn't download any files. After changing to my polish word everything works like a charm.

**Comment by lhark** [comment]
I knew this was a dirty way of doing that, thank you for the report, i'll look for a cleaner and more international way of doing it :)
