### ISSUE TITLE
'make' Issue

### ISSUE THREAD

**Issue by JusttDan** [lhark/truckersmp-cli#22]
Hey! I'm having an issue with the installation, when I try to run the 'make' command to complete the installation i get 

> make: Nothing to be done for 'all'.

I've installed mingw-w64 as required, maybe I'm doing something wrong here? I'm running Manjaro Linux and would love to be able to play ETS2MP!

**Comment by lhark** [comment]
truckersmp-cli.exe is already included with the repo (which is a terrible thing to do) because I judged cross-compilation to be too much to ask of the user. I would guess running `make clean` then `make` should work for you.

**Comment by JusttDan** [comment]
Just tried make clean then make and it started to work up until i got this error 

> make: *** [Makefile:6: truckersmp-cli.exe] Error 1

**Comment by lhark** [comment]
What do you get when you run this command ?
```
x86_64-w64-mingw32-gcc truckersmp-cli.c -o truckersmp-cli.exe
```

**Comment by JusttDan** [comment]
> [dan@Linux truckersmp-cli]$ x86_64-w64-mingw32-gcc truckersmp-cli.c -o truckersmp-cli.exe
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find crt2.o: No such file or directory
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find crtbegin.o: No such file or directory
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmingw32
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc_eh
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmoldname
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmingwex
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmsvcrt
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -ladvapi32
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lshell32
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -luser32
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lkernel32
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmingw32
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc_eh
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmoldname
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmingwex
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lmsvcrt
> /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find crtend.o: No such file or directory
> collect2: error: ld returned 1 exit status
> [dan@Linux truckersmp-cli]$

**Comment by lhark** [comment]
As I said, cross-compilation is not trivial.
It seems you are missing a few components to your mingw32 installation.

If that can help you, here are the mingw32 packages installed on my machine:
```
local/mingw-w64-binutils 2.29-1 (mingw-w64-toolchain mingw-w64)
    Cross binutils for the MinGW-w64 cross-compiler
local/mingw-w64-crt 5.0.3-1 (mingw-w64-toolchain mingw-w64)
    MinGW-w64 CRT for Windows
local/mingw-w64-gcc 7.3.0-1 (mingw-w64-toolchain mingw-w64)
    Cross GCC for the MinGW-w64 cross-compiler
local/mingw-w64-headers 5.0.3-1 (mingw-w64-toolchain mingw-w64)
    MinGW-w64 headers for Windows
local/mingw-w64-winpthreads 5.0.3-1 (mingw-w64-toolchain mingw-w64)
    MinGW-w64 winpthreads library
```

**Comment by lhark** [comment]
Also, you if you just want to play ETS2MP, you have no need to compile truckersmp-cli.exe. As I said, the compiled binary comes with the repository.

**Comment by JusttDan** [comment]
Okay, just downloaded a clean version, when running the command <code>./truckersmp-cli path to your ETS2 install folder</code> i get the response <code>ETS2 or ATS not found in GAMEDIR</code>

**Comment by lhark** [comment]
That's because you need to replace `path to your ETS2 install folder` with the actual path where you installed the game.
Do you have the singleplayer game working on wine ?

**Comment by JusttDan** [comment]
Yes, if i run steam through wine i can play ETS2 singleplayer
