### ISSUE TITLE
Log-file

### ISSUE THREAD

**Issue by spiderman82** [lhark/truckersmp-cli#28]
[FATAL ERROR] Cannot initialize logger (C:\users\spider\╨Ь╨╛╨╕ ╨┤╨╛╨║╤Г╨╝╨╡╨╜╤В╤Л\ETS2MP\logs\client_%s.log) - CLOSED

**Comment by spiderman82** [comment]
unable to locate library (/home/spider/.cache/truckersmp-cli\core_ets2mp.dll)

**Comment by Lucki** [comment]
[There's a similar error report at reddit:](https://old.reddit.com/r/SteamPlay/comments/9m5bbd/ssl_error_with_truckersmp_and_proton/eg2w0di/)

~~~
[FATAL ERROR] Cannot initialize logger (C:\users\perfectionist\╨Ь╨╛╨╕ ╨┤╨╛╨║╤Г╨╝╨╡╨╜╤В╤Л\ETS2MP\logs\client_%s.log)
[FATAL ERROR] Cannot use Logger::Log - no log file set!
~~~

**Comment by Lucki** [comment]
Closing in lack of feedback. Also all reports are really old and presumably aren't relevant anymore.
