### ISSUE TITLE
Why is OpenGL rendered disabled?

### ISSUE THREAD

**Issue by pruivo** [lhark/truckersmp-cli#42]
I'm using Proton 4.2 in old hardware (i5-2320 + GTX 760) and my frame rate was awful with DX9 with everything in low or disabled (it was "jumpy" inside the cities). 
I've enabled the OpenGL rendering and I was able to jump the settings to medium/high and with a smooth frame rate.

Is there any reason to be disabled?
I've been playing for a couple of days without any crash so far.

**Comment by Lucki** [comment]
You have to ask this question to [SCS Software](mailto:info@scssoft.com).

But you'll likely get an even better performance with D9VK which is currently experimentally added to Proton. See [here](https://github.com/lhark/truckersmp-cli/pull/40/commits/1d63bb69c1b8e4caefa11a5e6630c327432e78cb) or [here](https://github.com/lhark/truckersmp-cli/pull/31/commits/c0e8507454ab30a318bcbdb71ef628a46de47649) on how to add this functionality.

**Comment by pruivo** [comment]
I'm not sure if it is related to SCS. When I run the single-player, Steam asks if I want directx or opengl and this script doesn't.

I need to find a way to benchmark all the options available to see what fits best for me. In any case, I've my changes here: https://github.com/pruivo/truckersmp-cli/tree/t_opengl If someone wants to try.

**Comment by Traace** [comment]
I try your opengl version tomorrow :+1:

**Comment by kakurasan** [comment]
Alternatively, OpenGL renderer can be used by editing your `config.cfg`.

```
uset r_device "gl"
```

Default paths for Proton:

* ETS2: `~/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/drive_c/users/steamuser/My Documents/Euro Truck Simulator 2/config.cfg`
* ATS: `~/.local/share/truckersmp-cli/American Truck Simulator/prefix/pfx/drive_c/users/steamuser/My Documents/American Truck Simulator/config.cfg`

**Comment by kakurasan** [comment]
Fixed in 8aa88ca, OpenGL rendering backend is now used by default.
