### ISSUE TITLE
Unable to find ETS2 or ATS in this GAMEDIR. - Even after installing using truckersmp-cli

### ISSUE THREAD

**Issue by ghostlydot** [lhark/truckersmp-cli#43]
I hope I am not missing something totally obvious here, in case I do, I am sorry ;-;

First off: I installed ETS using the `./truckersmp-cli -eu -n [Username]` command. 
![image](https://user-images.githubusercontent.com/29519722/65389306-24bf8280-dd55-11e9-9a0c-30c3e1fe5645.png)
I assume this is how it should look like? 

Afterwards I tried the update and start command referenced in the readme:
`./truckersmp-cli -eusp -n [Username]` which seems to always run into errors for me
[Hastebin of the command output](https://hastebin.com/eqanuzidab.pl)
(my linux username and steam username have been replaced respectively in the command output)
While the script is running a few things happen: Steam opens up, tries to run ETS, actually gets it to display running in Steam (and shows that I am actually playing the game rn) but never opens up the game window. About where it displays "running..." next to the game the command displays `Unable to find ETS2 or ATS in this GAMEDIR.`

I also tried starting it with Wine (and a 64 bit install of Steam) which also caused errors for me. 
As said above I am probably just missing something totally obvious.

Looking up different issues I have seen the Proton warning near the end multiple times, I assume that isn't the error?

Thanks in advance for the help :)

**Comment by Lucki** [comment]
Please run `./truckersmp-cli -espv -n [Username]` and post the output. That should give some more information without restarting steam.

**Comment by ghostlydot** [comment]
```$ ./truckersmp-cli -espv
no moddir set and fallback found
/home/linuxUserName/github/truckersmp-cli/truckersmp
checking for errors
Game not found in /home/linuxUserName/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
Need to download (-u) the game?
removing /tmp/truckersmp-cli.5zA5fRqmBj and /tmp/truckersmp-cli.tmWij0lwyT
```
For some weird reason the folder specified is indeed totally empty, even though I downloaded the game prior (apparently). Using the install command: `./truckersmp-cli -eu -n [Username]` again, does not change anything, the data folder stays empty. Do I have to set the moddir by hand?

**Comment by Lucki** [comment]
> Do I have to set the moddir by hand?

That shouldn't be needed, that's only relevant for the files of TruckersMP which get now placed in the legacy path inside the script directory. Please also pass the `-v` argument to the install command: `./truckersmp-cli -euv -n [Username]`
Really strange that files aren't at the download path.

**Comment by ghostlydot** [comment]
Don't wanna spam the entire post with a long log: [truckersmp-cli-install-issue.log](https://github.com/lhark/truckersmp-cli/files/3644518/truckersmp-cli-install-issue.log)

Thank you again for your help. ;w;

**Comment by Lucki** [comment]
From what I can see is that the files should be in `$XDG_DATA_HOME/truckersmp-cli/Euro Truck Simulator 2/data`. The path gets correctly passed to `steamcmd` which reports it as installed in that location. Are you sure they aren't there? They're somewhere as `steamcmd` doesn't download them again and just verifies everything's there. Please search for `eurotrucks2.exe` as it _has_ to be somewhere. `find $XDG_DATA_HOME -name "eurotrucks2.exe"`

You're the first one I've seen with `steamcmd` installed system wide, I wonder if that's causing some problems.

**Comment by ghostlydot** [comment]
> You're the first one I've seen with `steamcmd` installed system wide, I wonder if that's causing some problems.

Thought I was supposed to...oof
```
$ find $XDG_DATA_HOME -name "eurotrucks2.exe"
./home/linuxUserName/.local/share/truckersmp-cli/Euro/bin/win_x64/eurotrucks2.exe
./home/linuxUserName/.local/share/truckersmp-cli/Euro/bin/win_x86/eurotrucks2.exe
```
Strangely enough it downloads all the files into the Euro directory (the Truck Simulator 2 part cut off; probably because of the space?). Moved all the files from the Euro directory to Euro Truck Simulator 2/data and the game loaded fine...with TruckersMP enabled.

Maybe some technical facts: I am using Arch with the bash shell.

**Comment by Lucki** [comment]
Yes, that's the space but that shouldn't matter because the string is quoted: https://github.com/lhark/truckersmp-cli/blob/8e95826bacab03044073fdba6c30fb4ebef97d36/truckersmp-cli#L337

The bug is already reported by @lhark and the maintainer refused to acknowledge it as a bug: 

> [In the steamcmd script, you must quote the "$@", or else arguments with spaces in their names will get split a second time.](https://aur.archlinux.org/packages/steamcmd#comment-691654)

> [Seeing as that script was taken with little modifications from Debian, I will leave it as is.](https://aur.archlinux.org/packages/steamcmd#comment-691655)

I recommend to uninstall `steamcmd` so this script downloads the script into userspace as it seems that the package won't get an update soon. Other option would be to manually edit the file which you'll probably have to do again on every update.

I also recommend to have a look into #31 if you're familiar with git as it'll allow to use the latest Proton 4.11 and has the ability to take the huge performance improvements given by d9vk.

Happy trucking!

**Comment by ghostlydot** [comment]
Will do that as soon as I have time :)

Thank you for the great help, removing steamcmd finally fixed the it for good

**Comment by Lucki** [comment]
> Suppose I should close the issue now?

If it is fixed: yes.
