### ISSUE TITLE
Workshop mods

### ISSUE THREAD

**Issue by Baltrust** [lhark/truckersmp-cli#46]
Is it only me or steam community workshop mods dont work in truckersmp-cli?
Im new to truckersmp-cli and I didnt have this problem in windows when i tried.

**Comment by Lucki** [comment]
They are downloaded but I also haven't got them to work. If you know how they'll get picked we can implement something to accomplish that.

**Comment by Klairm** [comment]
> They are downloaded but I also haven't got them to work. They're placed by default here: `$XDG_DATA_HOME/truckersmp-cli/$GAME/data/steamapps/workshop/content/$APPID/`
> 
> If you know how they'll get picked up we can implement something to accomplish that.

i don't have that folder and idk where's the pfx i'm using, what options i have?

**Comment by Klairm** [comment]
doesn't work for me

**Comment by CoccodrillooXDS** [comment]
TruckersMP doesn't support mods of any kind (except for Winter Mod and ProMods)

**Comment by Lucki** [comment]
Not entirely true since they're also allowing local mods through savegame editing (read the rules!). But nothing we can do about.
