### ISSUE TITLE
Support DXVK and enable FPS counter

### ISSUE THREAD

**Issue by squadramunter** [lhark/truckersmp-cli#47]
Please make DXVK working with the latest proton version: https://github.com/GloriousEggroll/proton-ge-custom

And add a option to enable the FPS counter for DXVK.

DXVK_HUD=fps,devinfo %command%

I tried running it on my normal steam cliënt but I don't know how to get this working on your script.

**Comment by kakurasan** [comment]
Unofficial version of Proton can be used (`-o /path/to/proton/dir` option is needed).

As of 8aa88ca, DXVK can be used when using official version of Proton (use `-c --enable-d3d11`).

If you want to use DXVK's FPS counter, you need to set `DXVK_HUD` when running `truckersmp-cli`.
Another option is FPS counter in Steam Overlay.
