### ISSUE TITLE
Unable to load mods

### ISSUE THREAD

**Issue by LinuxVieLoisir** [lhark/truckersmp-cli#49]
I tried to install promods but this one is not detected although I put it in the adapted folder.
Best regards.

**Comment by Christopher-S-25** [comment]
I have successfully installed promods and it does work on truckersmp without any issues.
Make sure that promods is updated, not corrupted and correctly installed, on the prefix used by truckersmp-cli. If you have downloaded the free version, make sure you have unzipped them correctly with 7z. I am using the latest steam proton with the prefix provided by the normal steam installation.

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
Hey, I was wondering what folder I put the promods files in...

**Comment by Lucki** [comment]
Closing cause there's no feedback. You can read up a bit more here: https://github.com/lhark/truckersmp-cli/issues/55#issuecomment-584125144
