### ISSUE TITLE
python3: can't open file '/home/alex/.local/share/truckersmp-cli/Proton/proton': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by WhyIsEveryUsernameIsAlreadyTaken** [lhark/truckersmp-cli#51]
So I was trying to install the launcher today but when I entered the following command './truckersmp-cli -s -e -p -u -n [my steam account name]' it says that there is no file or directory for 'Proton/proton'

Terminal Output:

Redirecting stderr to '/home/alex/.local/share/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] !!! Fatal Error: Steamcmd needs at least 250MB of free disk space to update.
threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x57d94380/0x0xf7730b'
Redirecting stderr to '/home/alex/.local/share/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] !!! Fatal Error: Steamcmd needs at least 250MB of free disk space to update.
threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x57113380/0x0xf773bb'
fatal: not a git repository (or any parent up to mount point /home/alex)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/tmp/truckersmp-cli 100%[===================>]   9.42K  --.-KB/s    in 0s      
/home/alex/.local/s 100%[===================>]   3.26M  2.49MB/s    in 1.3s    
/home/alex/.local/s 100%[===================>]   2.94M  2.31MB/s    in 1.3s    
/home/alex/.local/s 100%[===================>] 803.59K   917KB/s    in 0.9s    
/home/alex/.local/s 100%[===================>]   1.01M  6.06MB/s    in 0.2s    
/home/alex/.local/s 100%[===================>] 300.26K  --.-KB/s    in 0.09s   
/home/alex/.local/s 100%[===================>]   2.11M  7.35MB/s    in 0.3s    
/home/alex/.local/s 100%[===================>] 344.97K  --.-KB/s    in 0.09s   
Inotify-tools not installed, waiting 30 seconds for steam to start up.
python3: can't open file '/home/alex/.local/share/truckersmp-cli/Proton/proton': [Errno 2] No such file or directory

**Comment by Lucki** [comment]
> `[ 0%] !!! Fatal Error: Steamcmd needs at least 250MB of free disk space to update.`

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
So I reconfigured where my .local/share folder is so that I would have enough space and then I retried installing the launcher again...

Redirecting stderr to '/home/alex/bigdata/share/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Logging in user 'alcookie_gamezmc' to Steam Public ...
Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 0.03 (128539 / 506437594)
 Update state (0x5) validating, progress: 45.99 (232912411 / 506437594)
 Update state (0x5) validating, progress: 93.61 (474084891 / 506437594)
Success! App '1054830' fully installed.
Redirecting stderr to '/home/alex/bigdata/share/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
"@sSteamCmdForcePlatformType" = "windows"
Logging in user 'alcookie_gamezmc' to Steam Public ...
Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 3.19 (150994944 / 4727917093)
 Update state (0x5) validating, progress: 8.22 (388610149 / 4727917093)
 Update state (0x5) validating, progress: 13.25 (626641950 / 4727917093)
 Update state (0x5) validating, progress: 17.47 (825871390 / 4727917093)
 Update state (0x5) validating, progress: 22.70 (1073335326 / 4727917093)
 Update state (0x5) validating, progress: 27.32 (1291439134 / 4727917093)
 Update state (0x5) validating, progress: 32.37 (1530514462 / 4727917093)
 Update state (0x5) validating, progress: 37.47 (1771686942 / 4727917093)
 Update state (0x5) validating, progress: 42.57 (2012859422 / 4727917093)
 Update state (0x5) validating, progress: 47.59 (2249837598 / 4727917093)
 Update state (0x5) validating, progress: 52.55 (2484718622 / 4727917093)
 Update state (0x5) validating, progress: 57.52 (2719599646 / 4727917093)
 Update state (0x5) validating, progress: 62.67 (2962869278 / 4727917093)
 Update state (0x5) validating, progress: 67.81 (3206138910 / 4727917093)
 Update state (0x5) validating, progress: 72.25 (3415854110 / 4727917093)
 Update state (0x5) validating, progress: 77.26 (3652832286 / 4727917093)
 Update state (0x5) validating, progress: 82.45 (3898199070 / 4727917093)
 Update state (0x5) validating, progress: 87.37 (4130982942 / 4727917093)
 Update state (0x5) validating, progress: 92.52 (4374252574 / 4727917093)
 Update state (0x5) validating, progress: 97.31 (4600744990 / 4727917093)
Success! App '227300' fully installed.
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.
fatal: not a git repository (or any parent up to mount point /home/alex)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/tmp/truckersmp-cli 100%[===================>]   9.42K  --.-KB/s    in 0s      
Inotify-tools not installed, waiting 30 seconds for steam to start up.
Proton: Missing or invalid openvrpaths.vrpath file! [Errno 2] No such file or directory: '/home/alex/.config/openvr/openvrpaths.vrpath'
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198272704265 [API loaded no]
  _______              _                 __  __ _____
 |__   __|            | |               |  \/  |  __ \
    | |_ __ _   _  ___| | _____ _ __ ___| \  / | |__) |
    | | '__| | | |/ __| |/ / _ \ '__/ __| |\/| |  ___/
    | | |  | |_| | (__|   <  __/ |  \__ \ |  | | |
    |_|_|   \__,_|\___|_|\_\___|_|  |___/_|  |_|_|

[21:04:08] <info> [p3api] Game version is supported. Base address: 0000000000000000 Signature: db6abe3c1566
[21:04:08] <info> [net] [http async] Creating thread(s)[1]...
[21:04:08] <info> [net] [http async] Thread(s) created.
[21:04:08] <info> [client] Initialized successfully.
Unable to read VR Path Registry from C:\users\steamuser\Local Settings\Application Data\openvr\openvrpaths.vrpath
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
Fossilize INFO: Overriding serialization path: "/home/alex/bigdata/share/Steam/steamapps/shadercache/227300/fozpipelinesv4/steamapprun_pipeline_cache".

**Comment by Lucki** [comment]
Please try #31 because the master version is pretty much outdated at this time.

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
> Please try #31 because the master version is pretty much outdated at this time.

Hey, so I tried using the python script this time but i got the error:

Application Load error 3:0000065432

Terminal Output:

``/tmp/truckersmp-cli 100%[===================>]   8.83K  --.-KB/s    in 0s      
24245 24208
Proton: Missing or invalid openvrpaths.vrpath file! [Errno 2] No such file or directory: '/home/alex/.config/openvr/openvrpaths.vrpath'
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198272704265 [API loaded no]
  _______              _                 __  __ _____
 |__   __|            | |               |  \/  |  __ \
    | |_ __ _   _  ___| | _____ _ __ ___| \  / | |__) |
    | | '__| | | |/ __| |/ / _ \ '__/ __| |\/| |  ___/
    | | |  | |_| | (__|   <  __/ |  \__ \ |  | | |
    |_|_|   \__,_|\___|_|\_\___|_|  |___/_|  |_|_|

[17:44:13] <info> [p3api] Game version is supported. Base address: 0000000000000000 Signature: 9864276fd8ba
[17:44:14] <info> [net] [http async] Creating thread(s)[1]...
[17:44:14] <info> [net] [http async] Thread(s) created.
[17:44:14] <info> [client] Initialized successfully.

**Comment by Lucki** [comment]
https://github.com/lhark/truckersmp-cli/issues/34#issuecomment-504429293

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
I feel like every time I fix something there's always another error that I would need a fix for... This time the error when I launch the game is:

Euro Truck Simulator 2 can not access Steam
client. Suggested steps:

1. Check that the Steam client is running.
2. Check that you have updated version of the Steam
client.
3. Check that the automatic updates are enabled and the game is updated to the latest version.

Any new Tips or any suggestions on where to find a fix?
