### ISSUE TITLE
Not Able to Move Mouse Cursor In Main Menu

### ISSUE THREAD

**Issue by WhyIsEveryUsernameIsAlreadyTaken** [lhark/truckersmp-cli#54]
After finally getting truckersmp to work, I got into the game and wasn't able to move my mouse cursor, I'm not sure what's causing this, but if anyone has any tips, that would be great!

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
It would be great if someone could help me...

**Comment by Alexithymia2014** [comment]
Hi there, find the python script in the pull requests, use that and use the latest proton (5.0 for me). You should be able to use the cursor. If it gets stuck again cause of an alt tab I've hit shift tab to bring up the steam overlay. Then it works again!

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
> Hi there, find the python script in the pull requests, use that and use the latest proton (5.0 for me). You should be able to use the cursor. If it gets stuck again cause of an alt tab I've hit shift tab to bring up the steam overlay. Then it works again!

So I reinstalled truckersmp-cli from the the python port from the pull requests but I wasn't able to get the game to work/launch...

Got this error in the console:

ETS2 or ATS not found in GAMEDIR

**Comment by Alexithymia2014** [comment]
Did you run the update or whatever? I also had to specify my proton
directory.

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
I feel like you're being too specific... How do I specify "my proton directory" in the command?

**Comment by Alexithymia2014** [comment]
This is the command I'm using: /home/chris/truckersmp-cli/truckersmp-cli
-esp -n [steamname] -o "/home/chris/.steam/steam/steamapps/common/Proton
5.0/"
change the -e to -a if you want to run ats. add a u to the end of the p to
update it.

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
I tried doing the command you use to launch the game but I got this usage error:

Usage: ./truckersmp-cli [-huv] [-d path] GAMEDIR
  -d path     mod directory, defaults to $XDG_CACHE_HOME/truckersmp-cli
  -h          this help
  -u          update mod files only
  -v          verbose
  GAMEDIR     path to ETS2 od ATS game data, optional with -u

This is why I'm wondering if you're using the other version that I was using before you recommended me to use the version from the pull requests...

**Comment by Alexithymia2014** [comment]
Idk I'm pretty sure I'm using the python script... I'll send you what I
have later.

**Comment by Alexithymia2014** [comment]
[truckersmp-cli.zip](https://github.com/lhark/truckersmp-cli/files/4175727/truckersmp-cli.zip)

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
the version that you're using requires 4.11 to run properly... You can find more info [here](https://github.com/lhark/truckersmp-cli/issues/50).  Can you send me a link to where you got it from?

**Comment by Alexithymia2014** [comment]
Great! Glad to hear it! I am not touching the script since everything seems peachy haha. You should close this issue.

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
Wait, one more thing. I was wondering where to put the files for promods to play promods in mp...
