### ISSUE TITLE
Where do I put the promods files for truckersmp?

### ISSUE THREAD

**Issue by WhyIsEveryUsernameIsAlreadyTaken** [lhark/truckersmp-cli#55]
I'm unsure of where to put the scs files for promods to play truckersmp with promods...

**Comment by Christopher-S-25** [comment]
You place the extracted promods files inside the ETS2 prefix you use for truckersmp in this path:
`[prefix_path]/drive_c/users/[user]/My Documents/Euro Truck Simulator 2/mod`
where `[prefix_path]` is the path to the prefix and `[user]` is one of the users on the prefix that contains the *Euro Truck Simulator 2* folder inside *My Documents*. 
It basically works exactly the same as windows, but the path is a bit different. If you run on default settings, the prefix should be located inside the truckersmp-cli folder:
`truckersmp-cli/Euro Truck Simulator 2/prefix`

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
Found it... Thanks for telling me!
