### ISSUE TITLE
ETS2MP working under Ubuntu 16.04?

### ISSUE THREAD

**Issue by gerdneuman** [lhark/truckersmp-cli#6]
This is not really a bug report but I did not know any other way to ask.

Both my sons have ETS2 and would like to use Multiplayer mode now. `truckersmp-cli` is the best option I could find so far. So thanks for this 👍 

But before going into using/trying it I'd like to ask

1. Any known problems when running ETS2MP via Wine? (We have Ubuntu 16.04)
2. How severe is the performance penalty of running it via Wine instead of running it natively?
3. Is there a recommended Wine version? Ubuntu 16.04 comes with Wine 1.6.2, whereas the current version is Wine 2.0.2

**Comment by lhark** [comment]
Hello, don't worry about asking questions here, in fact I added a tag for future questions :)

So answer your questions:
1. The only way to run ETS2MP on linux is via wine, that's the reason why I had to develop this launcher. As for known problems the only thing I can think of is the fact that mouse interaction ingame with the multiplayer interface doesn't work. But that only prevents you from changing the radio frequency (ingame audio chat) and from reporting people. Other than that, the game is fully playable.
2. I run both the native and wine versions and didn't notice significative loss. Worst case scenario, just decrease the graphics settings a bit.
3. I run archlinux, so I don't think I ever tried a wine version below 1.9. But ETS2 is really easy to run on wine, I  wouldn't be surprised if it ran without any problem on wine 1.6 (actually I would love to have your feedback on that :) And if that doesn't work, installing a more recent version of wine on ubuntu seems pretty straightforward : https://www.linuxbabe.com/ubuntu/install-wine-devel-package-ubuntu-16-04

I hope I answered your questions in a satisfactory manner. Don't hesitate to come back for more information or to give some feedback on your installation.

**Comment by Clarin98** [comment]
It works for me, thanks a lot Ihark. I tried first with wine, and the cli program said that was impossible to create a process of 64 bits. After that, I tried with wine64 and all went ok.

My test was on Debian 9 Testing, wine-2.0.2, clean installation (without playonlinux or similar).

**Comment by lhark** [comment]
Thank you so much for your input :)
