### ISSUE TITLE
Mouse doesn't work in ETS2

### ISSUE THREAD

**Issue by pyramidenkoenig** [lhark/truckersmp-cli#66]
Hi there,
i tried truckersmp-cli today, first off, good work, seems like a lot of hours have gone into this. 
It starts without a problem, but when i'm in the Game neither my mouse or my xbox controller work.
(alltough i'm not sure about the Xbox controller, as i can't go into the seetings to configure it without a mouse)
Is there something i can do to fix this?

Thx in advance.
Here are my OS details:
`Fedora Workstation 32 with KDE Plasma 5.18.5`
`Kernel 5.6.11`
`QT Version 5.13.1`

**Comment by Lucki** [comment]
I'm not sure what could cause this. A few things you can try:

* Try disabling the steam overlay: `--disable-proton-overlay`
* When using an already existing savegame try with a temporary new prefix once: `--prefixdir "/tmp/directory/just/to/test"`
* Maybe a workshop mod is somewhat interfering, try renaming the mod folder temporary to test
* Try DX11: https://github.com/lhark/truckersmp-cli#direct3d-11-dxvk-or-wined3d

**Comment by Lucki** [comment]
Some more things to try:
* Open and close the steam overlay a few times, that's the advise from the other issue.
* Press Alt - that's the shortcut for TruckersMP to show the mouse in their overlay.
* Alt-Tab a few times.

Closing in lack of feedback.
