### ISSUE TITLE
Crashing when taking a boat

### ISSUE THREAD

**Issue by WantedFreak** [lhark/truckersmp-cli#7]
After selecting destination the game freezes. 

Linux w01f.home.local 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux
wine-2.12 (Staging)

**Comment by RockBomber** [comment]
It is happen  when you first time "teleporting"
Just wait about 20 minutes, then game will unfreezed
This is a feature of truckersMP, not a bug of linux client

**Comment by WantedFreak** [comment]
Ah. Just tried it now it works like normal. Maybe including that in the README would be good idea
