### ISSUE TITLE
Wrong EXE format

### ISSUE THREAD

**Issue by DiamandDragon** [lhark/truckersmp-cli#9]
When i'm start the launcher it reports back, that the format of the <b>truckersmp-cli.exe</b> is in a wrong format. This is for the version downloaded from github and for the self compiled version. 
Any ideas how to fix this problem?

**Comment by lhark** [comment]
Hello,

**truckersmp-cli.exe** isn't meant to be used on its own. You need to run the **truckersmp-cli** script that will run wine for you.

By the way, the wine prefix you use should be 64 bits, as ETS2MP doesn't support 32 bits installations of the game.

If you don't manage to solve your problem with the info I just provided you, could you please add some details to the issue, for example the output of the **truckersmp-cli** command, the version of wine you are using, and everything that you judge to be _relevant_ to the problem.
