### ISSUE TITLE
Game crashes when the user try to change tag color

### ISSUE THREAD

**Issue by Kazenin** [lhark/truckersmp-cli#91]
[comment]: # (Run your command with additional informational output [-v] and try to pinpoint the problem first.)

## Describe the bug
When I try to change tag color in truckersMP. the game is crashing

## Expected behavior
This the option I can't change:
![change_tag](https://user-images.githubusercontent.com/9669576/85913886-5a226080-b7fe-11ea-80db-727242109552.png)

## Command
~~~
I am running this command to start the game:
`./truckersmp-cli -esp -x "/steam/path/compatdata/227300/pfx"

~~~

## Terminal output
I receive this screen but not messages in terminal:
![crash](https://user-images.githubusercontent.com/9669576/85913935-c0a77e80-b7fe-11ea-9045-58682b726dd4.png)

## Information
 - OS: [Debian 10 Testing]
 - Proton or Wine version: [`Proton 4.11-13``]
 - truckersmp-cli version: [latest version]

I try to execute [these steps](https://forum.truckersmp.com/index.php?/topic/60695-game-crashes-when-the-user-try-to-change-de-playerfriendtag-color/) but no sucess. The config.txt files does not exist.

**Comment by Lucki** [comment]
Thank you for your bug report. We've encountered this before but unfortunately it looks like a bug in Wine/Proton.
The workaround you've found is basically the thing you want to do here.

> The config.txt files does not exist.

It should exist. Please try to find the config file by following along this guide https://github.com/lhark/truckersmp-cli/issues/50#issuecomment-568260892:

> The tag color can be changed by editing the value of tag_color in config.txt. The default paths (for Proton) are:
>
>    ETS2: `~/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/drive_c/users/steamuser/My Documents/ETS2MP/config.txt`
>    ATS: `~/.local/share/truckersmp-cli/American Truck Simulator/prefix/pfx/drive_c/users/steamuser/My Documents/ATSMP/config.txt`
>
> You can pick a color from any of "HTML color picker" web sites and use its decimal value.
> For example, if you want to use color #cccc00, specify 0xcccc00 = 13421568 and overwrite the file:
> ~~~
> {
>    "extra" : {
>       ...
>    },
>    "generals" : {
>       ...
>       "tag_color" : 13421568,
>       ...
>    },
>    ...
> ~~~
> python3 is useful to get decimal value:
> ~~~
> $ python3
> >>> 0xcccc00
> 13421568
> >>> (Ctrl-d)
> ~~~

**Comment by Kazenin** [comment]
Hey @Lucki thanks for answer.

I tried to find this path but it does not exist. Take a look:

ETS2:
![ets_mp](https://user-images.githubusercontent.com/9669576/85922722-17d34080-b84b-11ea-81f3-3a8d41ba9c5b.png)

ATS:
![ats_mp](https://user-images.githubusercontent.com/9669576/85922727-24f02f80-b84b-11ea-9dc1-759eac1884ff.png)

I tried to find config.txt file on entirely system but it does not exist. I am stuck at this point. I dont know how generate this path on my file system. I installed TrucksMP using the tips written here on github instructions.

**Comment by Lucki** [comment]
You've given a custom prefix location (`-x "/steam/path/compatdata/227300/pfx"`) so you have to look there:
`/steam/path/compatdata/227300/pfx/drive_c/users/steamuser/My Documents/ETS2MP/config.txt`

**Comment by Kazenin** [comment]
Gotcha!! It works!! I found the file and set tag color perfectly. Thank you so much @Lucki. Long life to truckersmp-cli and lets ride

**Comment by kakurasan** [comment]
Unfortunately this will most likely *not be fixed*.

* According to TruckersMP Support, this is a known bug
* Not sure whether TMP developers are trying to fix it or won't fix it
* I wanted to ask TMP developers (not Support staff) some questions but it was not possible

Most players use D3D11 on Windows and D3D11 doesn't have this issue. So this would be low priority... :disappointed:

**Comment by Lucki** [comment]
I've also tried to talk to them before about including real Linux support but they're pretty closed and don't want anyone to help.
We should keep an eye on the issue with DXVK (why `d3dcompiler_47.dll` is needed) so we don't need that activating anymore and can it make the default (at least for proton).
