### ISSUE TITLE
Recommend system wide installation of truckersmp-cli

### ISSUE THREAD

**Issue by squadramunter** [lhark/truckersmp-cli#96]
Hello, I followed the guide to install truckersmp-cli but I still recommend installing this as a system wide install.

Using pip install truckersmp-cli it install's only in the current directory.

With sudo -H pip3 install truckersmp-cli this problem has been solved. No need to add any parameters for system wide use.

**Comment by Lucki** [comment]
Never ever install something system wide with pip, no I won't recommend that **ever**.

If you would have read carefully the system-wide installation is already the most recommended installation method through your distros package repository system. If you'd like to have it in there ping their maintainer to include this.
