### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by squadramunter** [lhark/truckersmp-cli#97]
On my system when playing native ETS2 and Truckersmp-cli the sound of the horn is different. In truckersmp-cli it is more crackling and on native it's working like expected. I don't know why this is happening.

**Comment by Lucki** [comment]
Sounds like their new sound engine has problems with wine. Please verify the issue with 
* proton in steam in singleplayer and if it still persists report it to the proton bug tracker.
* plain wine and in singleplayer (`--singleplayer --wine`) and if it still persists report it at the wineHQ bugtracker.

**Comment by squadramunter** [comment]
Sorry I am using Proton version of it. I'll report back to you if I know the root cause of the problem.

**Comment by Lucki** [comment]
Sometimes pulse is doing weird stuff, maybe try some of these things:
* https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Glitches,_skips_or_crackling
* https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Choppy/distorted_sound

**Comment by Lucki** [comment]
Closing because lacking feedback.
